### ISSUE TITLE
Like a previous poster, my installation fails with this error

### ISSUE THREAD

**Issue by epmd34** [chrRtg/eve-skylizer#10]
Fatal error: Uncaught Zend\ServiceManager\Exception\ServiceNotFoundException: Unable to resolve service "MyLogger" to a factory; are you certain you provided it during configuration? in /Library/WebServer/Documents/eve-skylizer-master/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 687
--

But clearing the skylizer and browser caches does not help

**Comment by epmd34** [comment]
![image](https://user-images.githubusercontent.com/7251124/47659598-37552a00-db8d-11e8-80cd-e81279591df0.png)

**Comment by chrRtg** [comment]
The solution is most probably the same the previous poster metioned:

> Never mind, solved it by cleaning the cache. Some old config file (which was broken) was cached and used instead of the working one ...

How this is achieved: clear the caches with` rm -Rf ./data/cache/*`

Thanks to your valuable input I updated the last part of the installation documentation. Please also consider to have a brief look at the "updates" section in the wiki after your successful installation of Skylizer.

**Comment by epmd34** [comment]
Its not that. I'd already done what the former poster said, and also double checked paths to the data subdirectories and that permissions allow the server to write (confirmed OK as files are written to data/cache, nothing to data/log). I would welcome any other thoughts? I'm not sure how to approach an error arising deep in the Zend library.

**Comment by chrRtg** [comment]
May I kindly ask you to file then a more complete report, e.g. with your PHP version/configuration, the full error message, what's in the PHP log ...
You may put it into a ZIP file and send me the dowload link ingame to "Rtg Quack".

**Comment by chrRtg** [comment]
fixed
