### ISSUE TITLE
Better Filtering Options

### ISSUE THREAD

**Issue by orionshock** [chrRtg/eve-skylizer#11]
Would be nice to be able to use more than 1 option on the filters. 
The idea being to evaluate the moon based completely by it's Moon Goo aspects & ignore the normal minerals in the calculation.

**Comment by chrRtg** [comment]
Please may I ask you to elaborate your suggestion. You may tell me e.g. a story what you see, what you think and what you finally expect to get done.

From this perspective I may come up with some smart solution to match your expectation.

Fly safe

**Comment by orionshock** [comment]
The story, simply i'd like to be able to find out what moons are the best to put refineries on for only moon materials, the regular ore is not of interest to my group.

**Comment by chrRtg** [comment]
Maybe what your looking for:

- uncheck "show all moons"
- uncheck "Ore - Filter"
- check "Composition - Filter "
- click green link with constellatoin name
- click table header "value" or "ore-vale" to get the most valuable moons

Does this will give you the kind of view you're looking for?

**Comment by chrRtg** [comment]
not answered since 2 Month.
