### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by MokeyBytes** [chrRtg/eve-skylizer#13]
` -bash: ./bin/import-staticdata.sh: No such file or directory`

This is the error I am getting when trying to import static data... I'm following your instructions. But they are very vague. 

In `/bin/` I have `import-staticdata.sh` But it's not letting me import it because the dir doesn't exist... but it is there.

What could be causing this?

**Comment by MokeyII** [comment]
I seem to have figured out that issue.. but now it's telling me I cannot connect to mysql with the credentials... But I can connect manually with the same credentials

`./bin/import-staticdata.sh --host="localhost" --database="<skylizer>" --user="<skylizer@localhost>" --pass="password" -f`

Returns
`✖ can not connect to mysql with the given credentials with exit code 1`

**Comment by MokeyBytes** [comment]
Fixed that...
Now I can't update prices

`PHP Warning:  require(/var/www/html/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/bin/skylizer_console.php on line 7
PHP Fatal error:  require(): Failed opening required '/var/www/html/bin/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/bin/skylizer_console.php on line 7
`

**Comment by chrRtg** [comment]
Everything in the documentations assume you cd'ed to the application root directory. A ls (or dir on some machines) should show you directories like config, bin, public and more.

On a unix machine a `bash: ./bin/import-staticdata.sh` should show a reasonable result, but no error message.

From your decription above I assume you installed import-staticdata in your /bin directory.

**Comment by MokeyBytes** [comment]
I have, will fix tonight. Thanks.

**Comment by MokeyBytes** [comment]
Apparently I'm missing something or you just don't have something included in your instructions well enough. Installing through the applications root in `/var/www/html` to installing through unix root. It seems to just not want to work.

I got past the importing data, but updating prices is bringing an error
```
PHP Warning:  require(/var/www/html/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/bin/skylizer_console.php on line 7
PHP Fatal error:  require(): Failed opening required '/var/www/html/bin/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/bin/skylizer_console.php on line **7**```

Then assuming this isn't much of an issue, and after clearing the cache, Returns an Error 500.

This app does NOT want to work with me.

**Comment by MokeyBytes** [comment]
Ok, I figured most of it out. It was an issue with composer missing some PHP dependencies. 
Still can't get the page to show though. So I'm going to work on a clean template and attempt it one more time.
I'm going to start fresh and attempt it with

**Comment by MokeyBytes** [comment]
Even with a clean install, o errors, getting everything to install flawlessly, It still returns error 500.

My settings for PHP seem right.
```
<VirtualHost *:80>
    ServerName mywebsite.domain.com
    DocumentRoot /var/www/html/public

    <Directory /var/www/html/public/>
        DirectoryIndex index.php
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
```

**Comment by aaronmaynard** [comment]
@MokeyII how did you get past importing the static data? running`sudo ./import-staticdata.sh` from within bin Im receiving "command not found"

**Comment by chrRtg** [comment]
@aaronmaynard please always run the `./bin/import-staticdata.sh` while you cd'ed to your application root directory. A sudo should now neccessary.

**Comment by chrRtg** [comment]
@MokeyII does your install basically work? You may open in your browser http://<your-domain.tld>/_maintenance.html to test if the web server behave as expected when it comes to raw html files.
If yes please put a i.php into ./public/ with the following content:
`<?php
phpinfo();`

Then open in your browser `http://<your-domain.tld>/i.php`
Does this work, do you get a PHP-Info page?

**Comment by aaronmaynard** [comment]
@chrRtg I had attempted this first, later trying the sudo method mentioned.  I am currently trying to install this locally on my Ubuntu installation that is set up to mimic my hosting provider. Could this be causing some sort of issue, maybe down the line with the call back? When viewing the public dir in browser I am receiving  a <?php phpinfo(); notice, so I guess that's good?  

Side note: I was also wondering if the color scheme was customizable.

**Comment by aaronmaynard** [comment]
I have tried this on my windows pc as for the life of me I could not get composer to work properly on my linux machine.  I have come up with an error however, having to do with updating the databases.  I am receiving an unknown parameter` '[--host=127.0.0.1]'` and am left with the example which I fill as `./bin/import-staticdata.sh [--host="127.0.0.1"] --database="skylizer" [--user="root"] [--pass="pass"] -f`

**Comment by chrRtg** [comment]
if you receive problems with the import-staticdata please follow the instructions written in the documentation:

> If the script does not run in your environment you should follow the procedure as described in ./ressource/readme_update.txt

**Comment by aaronmaynard** [comment]
Followed the insructions in the readme_update.txt you mentioned.  I have decided to use AWS to host all of the database stuff since I will no longer have to mess with that over and over.  When I was installing this on a WAMP server following your instructions, I got the site to appear and function as normal.  I plan on hosting this on a raspberry pi, since my hosting provider does not allow ssh, and ftp caused errors since some documents were referencing the wamp dir, I have begun the process again on a RPi3 B+.  Following the same instructions I have a welcome page showing... perfect! However if I click on Log Into Eve or the About page then I am represented with 

> The requested URL /hyperion/public/about was not found on this server.
> The requested URL /hyperion/public/auth was not found on this server.

I have scrolled through some of the php documents and I believe that it may be the controller not forwarding to the application pages?  I have reinstalled dependencies via composer, cleared the cache, I dont know what to do from here.  Any guesses as to why they may not be firing to the correct pages?

**Comment by chrRtg** [comment]
According to issue #15 you already installed Skylizer but face issue withy your operating system or PHP installation. Please refer to my answer at this issue.

**Comment by aaronmaynard** [comment]
In case anyone else has issues in the future importing static data.  The command structure I needed was `mysql --user=root --password=mypass --database=dbname`. I unfortunately spent the latter part of the day trying to figure out why I was having access denied issues.  I'd also like to note that in my `mysql ?` help section it told me the structure for password was `--password[=name]`, so take things with a grain of salt and try out a few different things. 

 This is a guide for those who need to follow \ressource\readme_update.txt

**Comment by chrRtg** [comment]
Thank you for your valuable addition. I added a short section to wiki/Install. Do you thinks this improvement suffice?

**Comment by MokeyBytes** [comment]
yes, I'm going to give it another go today. *Crosses fingers*
