### ISSUE TITLE
Adding structure fails

### ISSUE THREAD

**Issue by 4tt1c** [chrRtg/eve-skylizer#16]
If i want to add a structure, the "Edit Structure" window pops up, i fill in the data and after saving the changes the structure is not listed.
Repeating the process doesn't change anything.

From nginx error.log:
2019/04/09 12:54:09 [error] 16866#16866: *8450 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: persist in /var/www/skylizer/module/VposMoon/src/Service/CosmicManager.php on line 310" while reading response header from upstream, client: THIS.IS.MY.IP, server: skylizer.MY.URL, request: "POST /vposmoon/editStructureJson/0 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "skylizer.MY.URL", referrer: "http://skylizer.MY.URL/vposmoon?system=30004703&filter_gooonly=1"

From skylizer atlog_*.log:
2019-04-09T12:54:09+02:00 DEBUG (7): editStructureAction() Array
(
    [moonid] => 12345678
    [structureid] =>
    [struct_item_id] => 12345
    [owning_corp] => 12345678
    [struct_name] => Random Name
)

**Comment by chrRtg** [comment]
problem fixed, thanks for your valuable issue description @4tt1c
