### ISSUE TITLE
does not like stand alone sql servers / static data

### ISSUE THREAD

**Issue by dstevens79** [chrRtg/eve-skylizer#17]
it would b really nice if i could use my already existing static data db
and would b cool if it didnt check for sql binary when importing - 

so ends up that i had to clone this on my sql server just to get it to import a dump of static data that i already have.... 

we have the technology to do this better i think ;)

thank you for your time and work on this project

**Comment by chrRtg** [comment]
Thank you for your suggestion and your kind words.
While my time is quite limited I would not find time to rework the core in the way you suggest. But feel free to contribute!

**Comment by dstevens79** [comment]
Skip forcing the binary check for sql

**Comment by chrRtg** [comment]
I feel I do not understand your suggestion. You refer to the shell script '/bin/import-staticdata.sh'? 

If yes, how should it import something to mysql without a mysql binary?
I assume you saw line 16 in the script which allows you to configure your own mysql binary, e.g. one for mariadb.

**Comment by dstevens79** [comment]
No sir, thT was not listed as something for me to look for in the
installation guide.
