### ISSUE TITLE
login - cannot find /auth 

### ISSUE THREAD

**Issue by dstevens79** [chrRtg/eve-skylizer#18]
i have spent about 4 hours attempting to resolve this before posting for help

https://i.imgur.com/OVGUsq2.png

i get that whenever i go to login

what am i doing wrong

plz - halp

**Comment by chrRtg** [comment]
While I have no idea what is working for you and if you had the chance to look into the apache, php and skylizer logfile it's very hard from my side to help you.
My first starting point would be to ask if any further route like /about or /dashboard is working for you.

**Comment by dstevens79** [comment]
no
no other link works
https://i.imgur.com/oj9VBO7.png

**Comment by chrRtg** [comment]
Then I would guess the Document root does not point to
`DocumentRoot /path/to/skylizer/public` or the .htaccess in /public does not work in your case.

**Comment by dstevens79** [comment]
ok i went to sleep and made some progress
its something to do with 
https://stackoverflow.com/questions/869092/how-to-enable-mod-rewrite-for-apache-2-2
this step is not in your guide, but seems to have resolved the issue for now... as links resolve properly

now i am getting 
Error code: 571885eb3a91664b8964da69849f0668
from my auth link

**Comment by dstevens79** [comment]
nope not fixed - now i have an internal 500

**Comment by dstevens79** [comment]
ok working... 
at this point i :
copied my local.php to a temp folder
removed the folder for eve-sky, 
recloned from github, 
reinstalled with composer,
added dirs,
set perms,
copied config back to autoload,
cleared cache,
restarted apache2
poof working

i place this here incase someone else ends up reading this with the same issue
