### ISSUE TITLE
Feature request: Search by ore-type.

### ISSUE THREAD

**Issue by jamiew0w** [chrRtg/eve-skylizer#19]
Hello!

First off, thanks for this tool, it's great!
There is one feature I'd like implemented that I think would be great QOL. Could we have the option of searching by ore-type or a filter for r64/r32 etc (ideally both) just to make it a bit more flexible.

Thanks again in the meantime!

**Comment by chrRtg** [comment]
Hi Jamie,
There is the "Composition - Filter " and the "Ore - Filter". They offer only what's in the scope. If you select a constellation and the constellation has been fully scanned you may expect a lot of various materials. 
What in particular you need on top? Maybe you tell me a little story what you in particular want to achieve and I come up with a solution :)

**Comment by jamiew0w** [comment]
Interesting, I didn't realise we could search by constellation. Would it be feasible to expand this up one tick to include searching by region?

Basically I'm looking for a way to get broader results. For example, if I was to fully scan an entire region it would be great to go back afterwards, search for loparite and get the direct results of where they all were (instead of going constellation by constellation).

**Comment by chrRtg** [comment]
Because of the huge number of possible results (imagine a "show all moons in Delve with xxx") I would resist to build it in this way. Maybe some functionality the system admin may enable from the config file. Let me think about it....

**Comment by jamiew0w** [comment]
I would still very much appreciate this. I have a handful of regions scanned so being able to check the database for r64/r32 (or just ore itself) by region would be very very useful. 

Perhaps a third dropdown underneath the composition/ore filters for 'rarity' with the options r8/16/32/64?

If it was expanded to include 'region' alongside constellation too I think this tool would be perfect.
