### ISSUE TITLE
"Owning Corporation" part of moon structures seem to be broken

### ISSUE THREAD

**Issue by Destroyer140** [chrRtg/eve-skylizer#23]
Hi,

I decided to fully map up the moons of my home system and the citadels of the "occupied" moons, however whenever I try to add the owning corporation of the athanor's nothing comes up to corp name, nor the corp tag (while it can perfectly find my own).

It's not even that they are really fresh corps as some has been close to 10 year old. 1 such example corporation for testing purposes would be "76RUS - YAR Group"

**Comment by chrRtg** [comment]
Did you loaded your database? Please refer to 'Update Alliance and Corporation data' in the Wiki.



Am 24. Juli 2019 17:56:44 WESZ schrieb Destroyer140 <notifications@github.com>:
>Hi,
>
>I decided to fully map up the moons of my home system and the citadels
>of the "occupied" moons, however whenever I try to add the owning
>corporation of the athanor's nothing comes up to corp name, nor the
>corp tag (while it can perfectly find my own).
>
>It's not even that they are really fresh corps as some has been close
>to 10 year old. 1 such example corporation for testing purposes would
>be "76RUS - YAR Group"
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/chrRtg/eve-skylizer/issues/23

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Destroyer140** [comment]
Hi,
Sorry for the late response. I wasn't aware that skylizer is a tool you were meant to install and used it on  what I assume to be it's home page https://skylizer.eve-tools.info/index.

Is this something you are supposed to host on a server or something or could it work as an "on demand" tool that I just run and use locally whenever I need?

**Comment by tonytonyistony** [comment]
@Destroyer140 
Skylizer is an open source project that can be loaded on your own web server to be served to the public or accessed within your LAN for personal use.
The developer also has his own server available for public use. Better to keep your intel to yourself though.

**Comment by chrRtg** [comment]
@tonytonyistony is perfectly right, thanks for your answer.

While the original question seems to be answered I'll close this issue. Feel free to re-open or to submit a new in case you found a problem or have a suggestions.
