### ISSUE TITLE
PHP Notice:  Undefined variable: scan_res in ScanManager.php on line 96

### ISSUE THREAD

**Issue by tonytonyistony** [chrRtg/eve-skylizer#24]
I just installed a fresh copy of skylizer, and everything seemed to be working good until I tried pasting in a scan result. In the UI it says that the scan was successful, however nothing is populated. I checked the apache2 logs to see if anything stood out and I found this.

`PHP Notice:  Undefined variable: scan_res in /var/www/eve-skylizer/module/VposMoon/src/Service/ScanManager.php on line 96, referer: http://skylizer._redacted_.com/vposmoon?system=30003023`

Any assistance would be appreciated. @chrRtg 
EDIT:
I went on your public site and tried to paste in the scan results and it also doesn't work. 
Scan details below...
> VKU-BG I - Moon 1
	Bitumens	0.1754264236	45492	30000927	30000927	40059150
	Flawless Arkonor	0.3133094311	46678	30000927	30000927	40059150
	Opulent Pyroxeres	0.1710040569	46686	30000927	30000927	40059150
	Sylvite	0.3402600884	45491	30000927	30000927	40059150 

To make sure that I had the formatting correct, i tried another scan result from another system. This scan worked.
>Gerper I - Moon 1
	Bitumens	0.344790995121	45492	30003023	40191834	40191835
	Dazzling Spodumain	0.220836445689	46688	30003023	40191834	40191835
	Stable Veldspar	0.241074964404	46689	30003023	40191834	40191835
	Zeolites	0.193297609687	45490	30003023	40191834	40191835 

I also could not delete the scan results. Neither on my server which Im an administrator, nor on your public server.

**Comment by tonytonyistony** [comment]
@chrRtg 
I went on your public site and tried to paste in the scan results and it also doesn't work. 
Scan details below...
> VKU-BG I - Moon 1
	Bitumens	0.1754264236	45492	30000927	30000927	40059150
	Flawless Arkonor	0.3133094311	46678	30000927	30000927	40059150
	Opulent Pyroxeres	0.1710040569	46686	30000927	30000927	40059150
	Sylvite	0.3402600884	45491	30000927	30000927	40059150

**Comment by chrRtg** [comment]
Thanks for your valuable input. The problem showing always an error message has been fixed. I also improved the info messages shown after a moon scan has been processed. Now It shows you the moons as well the number of ore types found in your scan.

The problem with your scan of "VKU-BG I - Moon 1" is an error with the data given. The last number for each goo is the ID of the moon. But the ID 40059150 in your scan resolves to the planet, not his first moon. This seems to be a data error you may report to CCP.

**Comment by tonytonyistony** [comment]
@chrRtg How did you go about checking those ID's to find out it returned a planet? 
I'd like to check on my end as well.

**Comment by chrRtg** [comment]
Sure mate, you're welcome.

The ID of a moon in a moon scan is the last element in the row with the goo. In your case for "VKU-BG I - Moon 1" the moon Id is 40059150. But this ID resolves to a planet "VKU-BG I":
https://esi.evetech.net/latest/universe/moons/40059150/?datasource=tranquility

The ID of the moon we're looking for is 40059151. 
https://esi.evetech.net/latest/universe/moons/40059151/?datasource=tranquility

I have no clue why, but your scan is borked. If you get the same results scanning this very moon again I would suggest to file a report toward CCP. In this case you may refer or copy my text above.
