### ISSUE TITLE
Feature Request: Delete Previous Scanned Moon Results

### ISSUE THREAD

**Issue by tonytonyistony** [chrRtg/eve-skylizer#25]
IDK if Im doing it wrong, but I have yet been able to delete moon data after its been imported. As of right now I cant correct errors without diving into the DB or just a complete wipe of the DB.

**Comment by chrRtg** [comment]
Thanks for your suggestion.
Removing the scanned moongoo from a moon is now available. It requires a role of moon.mange or admin. The regular user is not able to perform a deletion.
