### ISSUE TITLE
PHP7.4 compatibility issues

### ISSUE THREAD

**Issue by jamiew0w** [chrRtg/eve-skylizer#34]
Hello!

It looks like certain parts of this code aren't compatible with PHP7.4 sadly. When doing a search for constellations and ore type we come across this error:

```
2020/05/27 01:17:25 [error] 369#369: *88927 FastCGI sent in stderr: "line 177PHP message: PHP Notice:  Trying to access array offset on value of type float in /var/www/bleh/module/VposMoon/src/View/Helper/VposMoonHelper.php on line 177
```

The line in question being the third line in this function:

```
   private function sortWorthForRenderMoonMateriallist($a, $b)
    {
        return $a["worth"] <= $b["worth"];
    }
```

Would it be possible to get it updated for PHP7.4 compatibility to ensure it's good for the next 18-30 months?

https://www.php.net/supported-versions.php

**Comment by chrRtg** [comment]
Do you experience any problems with the application?

**Comment by jamiew0w** [comment]
Yeah, I gave a quick rundown above. If you'd like I can re-enable and grab more logs, it's basically just install php7.4 & necessary php-modules - switching the socket and test. 

I'll debug it a bit more this evening when I get some time.

**Comment by jamiew0w** [comment]
put up a [pr](https://github.com/chrRtg/eve-skylizer/pull/35) with a proposed fix, please check it over - I'm terrible at PHP
