### ISSUE TITLE
Error in the Wiki

### ISSUE THREAD

**Issue by H4Z4RD-H42** [chrRtg/eve-skylizer#7]
after done this 2 commands
`cd ./ressource/db_import/`
`bunzip2 *.bz2`

i see only a `.mysql` file inside folder, so, this command not work
`mysql skylizer -u root -p <./sl_full_dump_*.sql`

This command do the job:
`mysql skylizer -u root -p <./*.mysql`

**Comment by chrRtg** [comment]
Thank you for the hint. It's my faul, packed the dump with the wrong extension. I'll fix the file soon.
