### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by Rayvenhaus** [chrRtg/eve-skylizer#8]
Just got Skylizer installed and running.  Took awhile to get everything configured, but we're looking good. I see the front page and all's well there, however EVE SSO is not working.  I get directed to the EVE Website to log in and when I log in there, I get this:

{"error":"invalid_request","error_description":"Some parameters are either missing or invalid"}

**Comment by chrRtg** [comment]
It't most likely a problem with the eve__sso configuration in /config/autoload/local.php.dist
 or the entry with the EVE Online developers portal.

But before you try again. After each change in the configuration files please emtpy the application caches with ´rm -Rf ./data/cache/*´. Sometimes the EVE login server had not responded well and if this happen while you did the configuration you probably got lost.

If nothing helps you may send me your most current logfile. It's located in ´data/log/atlog_xxx_log`.

**Comment by Rayvenhaus** [comment]
That was it, I was able to clear the cache and that error went away.
