### ISSUE TITLE
Callback incorrect

### ISSUE THREAD

**Issue by Rayvenhaus** [chrRtg/eve-skylizer#9]
Previous SSO issue fixed, however, the callback URL does not work:

Callback setting in local.php:
                'clientId'          => '***********************************',
                'clientSecret'      => '*********************************************',
                'redirectUri'       => 'https://skylizer.thedoubled.org/auth/index',

Application settings:
APPLICATION SETTINGS:
Your applications authentication settings. The "Secret Key" should never be human-readable in your application.

Client ID: **************************************
Secret Key: ************************************************
Callback URL: https://skylizer.thedoubled.org/auth/index
Scopes: 
publicData
esi-location.read_location.v1

After successfully logging in via SSO, callback returns this:

Not Found
The requested URL /index was not found on this server.

However, if I then go to https://skylizer.thedoubled.org I am logged in.

**Comment by chrRtg** [comment]
Quick Check:
https://skylizer.thedoubled.org/auth/index
is working fine.

If EVE SSO redirects you to https://skylizer.thedoubled.org/index then the "callback URL" you entered in the developer portal (https://developers.eveonline.com/applications) is most probably wrong.

**Comment by Rayvenhaus** [comment]
As shown above and in the screen shot, the callback URL is entered as the wiki indicates.

![2018-07-22 07_12_19-application details - eve_ developers](https://user-images.githubusercontent.com/4164076/43045034-eb9679fe-8d7e-11e8-85c2-a6fd6f7ecee2.png)

**Comment by Rayvenhaus** [comment]
It appears that I am getting a 302 error:

Apache Access log
73.99.10.81 - - [22/Jul/2018:11:13:16 +0000] "GET /auth/index HTTP/1.1" 302 4234 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
73.99.10.81 - - [22/Jul/2018:11:13:22 +0000] "GET /auth/index?code=*** HTTP/1.1" 302 499 "https://login.eveonline.com/$
73.99.10.81 - - [22/Jul/2018:11:13:24 +0000] "GET /index HTTP/1.1" 404 461 "https://login.eveonline.com/oauth/authorize?scope=publicData+esi-location.read_location.v1&state=***&response_type$
73.99.10.81 - - [22/Jul/2018:11:13:25 +0000] "GET /favicon.ico HTTP/1.1" 404 4293 "https://skylizer.thedoubled.org/index" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.339$

Apache Error Log
[Sun Jul 22 11:13:24.350063 2018] [negotiation:error] [pid 11241] [client 73.99.10.81:55317] AH00687: Negotiation: discovered file(s) matching request: /var/www/skylizer/public/index (None could be negotiated)., referer$

**Comment by Rayvenhaus** [comment]
![2018-07-22 07_12_19-application details - eve_ developers](https://user-images.githubusercontent.com/4164076/43045108-741dc3e4-8d80-11e8-9820-fcbd7802ae2f.png)

As I showed above, those are the settings from the local.php and the Application at Eve Developers.

It appears that I am getting a 302 redirect when accessing that URL:"

Apache Access log
73.99.10.81 - - [22/Jul/2018:11:13:16 +0000] "GET /auth/index HTTP/1.1" 302 4234 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
73.99.10.81 - - [22/Jul/2018:11:13:22 +0000] "GET /auth/index?code=*** HTTP/1.1" 302 499 "https://login.eveonline.com/$
73.99.10.81 - - [22/Jul/2018:11:13:24 +0000] "GET /index HTTP/1.1" 404 461 "https://login.eveonline.com/oauth/authorize?scope=publicData+esi-location.read_location.v1&state=***&response_type$
73.99.10.81 - - [22/Jul/2018:11:13:25 +0000] "GET /favicon.ico HTTP/1.1" 404 4293 "https://skylizer.thedoubled.org/index" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.339$

Apache Error Log
[Sun Jul 22 11:13:24.350063 2018] [negotiation:error] [pid 11241] [client 73.99.10.81:55317] AH00687: Negotiation: discovered file(s) matching request: /var/www/skylizer/public/index (None could be negotiated)., referer$

**Comment by chrRtg** [comment]
Sorry, probably missed that.

Short version:
https://skylizer.thedoubled.org/index does not work.

Long version:
If the login went well EVE SSO calls your Callback URL. Then skylizer process the request. If the Login is fine Skylizer forwards the user to the URL /index, the main entry point. From here Skylizer detects you've been logged on and forwards you to the Dashboard (https://skylizer.thedoubled.org/dashboard).

Hope this give you some idea whats going wrong.
